CREATE TABLE IF NOT EXISTS mpa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS films (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    releaseDate date NOT NULL,
    duration integer NOT NULL,
    mpa integer NOT NULL REFERENCES mpa (id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS genres (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS films_genres (
    film_id integer REFERENCES films (id) ON DELETE CASCADE,
    genre_id integer REFERENCES genres (id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, genre_id)
);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    login varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    birthday date NOT NULL
);
CREATE TABLE IF NOT EXISTS films_likes (
    film_id integer REFERENCES films (id) ON DELETE CASCADE,
    user_id integer REFERENCES users (id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS friendship_status (
    user_id integer REFERENCES users (id) ON DELETE CASCADE,
    friend_id integer REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);